### ISSUE TITLE
Déploiement avec GitHub Pages

### ISSUE THREAD

**Issue by gaetanmaisse** [fnazih/First-Resume#1]
_Ton repository est arrivé dans ma homepage GitHub et je n'ai pas pu m'empecher de jeter un oeil._

Comme ton repository contient un site statique tu peux le déployer de facon automatique.
Il faut aller dans `Settings > Options > GitHub Pages` et choisir la branche que tu veux deployer (`main`).

Juste avec ça tu devrais pouvoir retrouver ton site sur `https://fnazih.github.io/First-Resume/CV.html`🚀 .

**Comment by fnazih** [comment]
Bonjour monsieur,

Quelle bonne surprise de recevoir ce genre d’e-mail! Merci beaucoup pour
votre conseil, je n’hésiterai pas à l’appliquer ce soir! En plus je m’étais
justement demandé comment l’héberger gratuitement pour qu’il soit
disponible à distance sans avoir à upload le dossier GitHub

Je vous souhaite une bonne fin de weekend et vous dis à très bientôt,
NAZIH Fatima-Zohra.
